=== ritamganguli/racv_hyperX/src/test/resources/maps/ObjectMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="class">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="screen" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="xpath" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="objectId" type="xs:string" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="screenId" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ritamganguli/racv_hyperX/src/test/resources/maps/ObjectMap-Prod.xml
<?xml version="1.0" encoding="UTF-8"?>
<class xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ObjectMap.xsd">
	<screen screenId="aemSitesPage">
		<xpath objectId="aemEditorLoadingAnimation">//coral-wait</xpath>
	</screen>
	<!-- START - assistanceBySmsPage -->
	<screen screenId="assistanceBySmsPage">
		<xpath objectId="title">//div[@data-placeholder='Select your title']//div[@id='combo1']</xpath>
		<xpath objectId="titleOption">//div[@data-value='Mr']</xpath>
		<xpath objectId="firstName">//input[@name='First_Name__c']</xpath>
		<xpath objectId="lastName">//input[@name='Last_Name__c']</xpath>
		<xpath objectId="memberNumber">//*[@name="Member_Number__c"]</xpath>
		<xpath objectId="address">//*[@name='Street_Name__c']</xpath>
		<xpath objectId="suburb">//*[@name="City__c"]</xpath>
		<xpath objectId="state">//div[contains(@data-placeholder,'Select your state')]//div[@id='combo1']</xpath>
		<xpath objectId="stateValue">//div[@data-value='VIC']</xpath>
		<xpath objectId="postcode">//*[@name="Postal_Code__c"]</xpath>
		<xpath objectId="email">//*[@name="Email__c"]</xpath>
		<xpath objectId="mobile">//*[@name="Mobile_Phone__c"]</xpath>
		<xpath objectId="submitButton">//span[normalize-space()='Submit']</xpath>
	</screen>
	<!-- END - assistanceBySmsPage -->
	<!-- START - bikeAssistEFormPage -->
	<screen screenId="bikeAssistEFormPage">
		<xpath objectId="firstName">//*[@id="firstnameId"]</xpath>
		<xpath objectId="lastName">//*[@id="lastnameId"]</xpath>
		<xpath objectId="dob">//*[@id="Date_of_Birth_Text__cId"]</xpath>
		<xpath objectId="email">//*[@id="emailId"]</xpath>
		<xpath objectId="contactNumber">//*[@id="mobileId"]</xpath>
		<xpath objectId="streetAddress">//*[@id="streetId"]</xpath>
		<xpath objectId="suburb">//*[@id="suburbId"]</xpath>
		<xpath objectId="postcode">//*[@id="postalcodeId"]</xpath>
		<xpath objectId="state">//*[@id="stateId"]</xpath>
		<xpath objectId="partnerCode">//*[@id="Promo CodeId"]</xpath>
		<xpath objectId="termsAndConditions">//*[@id="checkbox-wrap"]/label[contains(text(),'Purchaser')]</xpath>
		<xpath objectId="marketingConsent">//*[@id="checkbox-wrap"]/label[contains(text(),'Keep me')]</xpath>
		<xpath objectId="submitButton">//*[@class="submit section"]/div/div[2]/input[2]</xpath>
	</screen>
	<!-- END - bikeAssistEFormPage -->
	<!-- START - clubFormPage1 -->
	<screen screenId="clubFormPage1">
		<xpath objectId="pageTitle">//*[@id="par_bookingwidget"]/h3</xpath>
		<xpath objectId="checkInDatePicker">//*[@id="checkin-temp"]</xpath>
		<xpath objectId="checkInDatePickerNxtMonth">//*[@class="datepicker-days"]/table/thead/tr[2]/th[3]</xpath>
		<xpath objectId="checkInDatePickerDay5">(//*[@class="datepicker-days"]/table/tbody/tr/td[@class="day"])[5]</xpath>
		<xpath objectId="checkOutDatePicker">//*[@id="checkout-temp"]</xpath>
		<xpath objectId="checkOutDatePickerNxtMonth">//*[@class="datepicker-days"]/table/thead/tr[2]/th[3]</xpath>
		<xpath objectId="checkOutDatePickerDay9">(//*[@class="datepicker-days"]/table/tbody/tr/td[@class="day"])[9]</xpath>
		<xpath objectId="adults">//*[@id="adults"]</xpath>
		<xpath objectId="children">//*[@id="children"]</xpath>
		<xpath objectId="availibilityButton">//*[@id="check"]</xpath>
		<xpath objectId="backToRacvMainLink">//*[@data-description="Back to RACV main site"]</xpath>
	</screen>
	<!-- END - clubFormPage1 -->
	<!-- START - clubFormPage2 -->
	<screen screenId="clubFormPage2">
		<xpath objectId="pageTitle">//*[@class="u-spacing-bottom-small"]</xpath>
		<xpath objectId="membershipNumber">//*[@id="input-name-2"]</xpath>
		<xpath objectId="familyName">//*[@id="input-name-family"]</xpath>
		<xpath objectId="submitButton">//button[@value="Submit"]</xpath>
		<xpath objectId="memberValidationError">//p[text()="The club member number or family name were unable to be validated. Please try again."]</xpath>
	</screen>
	<!-- END - clubFormPage2 -->
	<!-- START - clubFormPage3 -->
	<screen screenId="clubFormPage3">
		<xpath objectId="selectFirstRoom">//*[@id="room0"]</xpath>
		<xpath objectId="addRoomCheckout">//*[@id="selectRoomBtn0"]</xpath>
	</screen>
	<!-- START - clubFormPage3 -->
	<!-- START - clubLetterPage1 -->
	<screen screenId="clubLetterPage1">
		<xpath objectId="clubLetterheader">//*[@id="rte0.07296021760754312"]/div/h3</xpath>
		<xpath objectId="membershipNumber">//*[@id="input-membership1"]</xpath>
		<xpath objectId="memberTitle">//*[@id="titleId"]</xpath>
		<xpath objectId="memberFirstName">//*[@id="input-name"]</xpath>
		<xpath objectId="memberLastName">//*[@id="input-lastname"]</xpath>
		<xpath objectId="visitStartCalendarIcon">//*[@title="start Of Visit"]</xpath>
		<xpath objectId="visitStartCalendarNextMonth">//*[@class="datepicker-days"]/table/thead/tr[2]/th[3]</xpath>
		<xpath objectId="visitStartCalendarDate">//*[@class="datepicker-days"]/table/tbody/tr/td[@class="day"]</xpath>
		<xpath objectId="visitEndCalendarIcon">//*[@title="end Of Visit"]</xpath>
		<xpath objectId="visitEndCalendarNextMonth">//*[@class="datepicker-days"]/table/thead/tr[2]/th[3]</xpath>
		<xpath objectId="visitEndCalendarDate">(//*[@class="datepicker-days"]/table/tbody/tr/td[@class="day"])/following-sibling::node()</xpath>
		<xpath objectId="visitStartTextBox">//*[@id="Event_Start_Time__c"]</xpath>
		<xpath objectId="visitEndTextBox">//*[@id="Event_End_Time__c"]</xpath>
		<xpath objectId="memberEmail">//*[@id="email"]</xpath>
		<xpath objectId="phoneHome">//*[@id="home"]</xpath>
		<xpath objectId="phoneMobile">//*[@id="mobile"]</xpath>
		<xpath objectId="deliveryEmailMethod">//*[@id="deliveryTypeEmail to me"]</xpath>
		<xpath objectId="declarationCheckbox">//*[@id="checkbox-label"]</xpath>
		<xpath objectId="submit">//*[@id="submit2"]</xpath>
		<xpath objectId="errorMessage">//*[text()[contains(., 'Please Enter Valid Club Membership Details')]]</xpath>
	</screen>
	<!-- END - clubLetterPage1 -->
	<!-- START - contactRACVFormPage1 -->
	<screen screenId="contactRACVFormPage1">
		<xpath objectId="contactRACVFormPage1Message">//*[@id="personal-details"]/div[1]/h3</xpath>
		<xpath objectId="membershipId">//input[@name="Member_Number__c"]</xpath>
		<xpath objectId="firstName">//input[@name="First_Name__c"]</xpath>
		<xpath objectId="lastName">//input[@name="Last_Name__c"]</xpath>
		<xpath objectId="email">//input[@name="Email__c"]</xpath>
		<xpath objectId="phoneNumber">//input[@name="Mobile_Phone__c"]</xpath>
		<xpath objectId="natureOfBusinessDropDown">//div[@id="combo1"]</xpath>
		<xpath objectId="natureOfBusinessFeedbackResult">//div[@role="option"][@data-value="Feedback"]</xpath>
		<xpath objectId="comments">//textarea[@name="Comments__c"]</xpath>
		<xpath objectId="submitButton">//button[@value="submit"]</xpath>
		<xpath objectId="copyReferenceText">//button[@class="cmp-copyButton__container"]/span[contains(.,"FMD")]</xpath>
		<xpath objectId="memberValidationError">//p[@class="cmp-form__error-notification__text"]/p[text()="Sorry, the member number you've entered is invalid. Please try again."]</xpath>
	</screen>
	<!-- END - contactRACVFormPage1 -->
	<!-- START - contactRACVFormPage2 -->
	<screen screenId="contactRACVFormPage2">
		<xpath objectId="referenceNumber">//span[@class="referenceNumber"]</xpath>
	</screen>
	<!-- END - contactRACVFormPage2 -->
	<!-- START - memberDiscountsHomePage -->
	<screen screenId="memberDiscountsHomePage">
		<xpath objectId="pageTitle">//*[@class="u-proxima-nova-xlarge "]</xpath>
		<xpath objectId="popularTab">//ul[@class="cmp-benefitssnapshotpanel--tabList"]/li[@data-description="popular"]</xpath>
		<xpath objectId="popularTabSelected">//ul[@class="cmp-benefitssnapshotpanel--tabList"]/li[contains(@class,"selected")][@data-description="popular"]</xpath>
		<xpath objectId="popularDiscount1Picture">//div[@id="tab1"]/div/a[1]/div/picture</xpath>
		<xpath objectId="popularDiscount10Picture">//div[@id="tab1"]/div/a[10]/div/picture</xpath>
		<xpath objectId="shoppingTab">//ul[@class="cmp-benefitssnapshotpanel--tabList"]/li[@data-description="shopping"]</xpath>
		<xpath objectId="shoppingTabSelected">//ul[@class="cmp-benefitssnapshotpanel--tabList"]/li[contains(@class,"selected")][@data-description="shopping"]</xpath>
		<xpath objectId="shoppingDiscount1Picture">//div[@id="tab3"]/div/a[1]/div/picture</xpath>
	</screen>
	<!-- END - memberDiscountsHomePage -->
	<screen screenId="movieTicketsPage2-p3">
		<xpath objectId="membershipNumber">//input[@name="membershipNo"]</xpath>
		<xpath objectId="memberFamilyName">//input[@name="lastname"]</xpath>
		<xpath objectId="submitButton">//span[text()="Submit"]/..</xpath>
		<xpath objectId="invalidMemberError">//p[text()[contains(., 'The member number or family name were unable to be validated. Please try again.')]]</xpath>
	</screen>
	<!-- START - racvHomePage -->
	<screen screenId="racvHomePage">
		<xpath objectId="closeEmergencyBanner">//button[contains(@class,'c-btn-close--emergency')]</xpath>
		<xpath objectId="iWantToWidget">//*[@class="iwantto qlink"]</xpath>
		<xpath objectId="myMembershipFooterLink">//*[@id="footer_footer_footerlinks"]/li[1]/a</xpath>
		<xpath objectId="racvClubFooterLink">//*[@id="footer_footer_footerlinks"]/li[2]/a</xpath>
		<xpath objectId="racvResortsFooterLink">//*[@id="footer_footer_footerlinks"]/li[3]/a</xpath>
		<xpath objectId="racvShopsFooterLink">//*[@id="footer_footer_footerlinks"]/li[4]/a</xpath>
		<xpath objectId="careersFooterLink">//*[@id="footer_footer_footerlinks"]/li[5]/a</xpath>
		<xpath objectId="aboutRACVFooterLink">//*[@id="footer_footer_footerlinks"]/li[6]/a</xpath>
		<xpath objectId="privacyCharterFooterLink">//*[@id="footer_footer_footerlinks"]/li[7]/a</xpath>
		<xpath objectId="legalFooterLink">//*[@id="footer_footer_footerlinks"]/li[8]/a</xpath>
		<xpath objectId="sitemapFooterLink">//*[@id="footer_footer_footerlinks"]/li[9]/a</xpath>
